// <auto-generated />
using System;
using CS2Cases.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CS2Cases.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CS2Cases.Models.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Cases", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Откройте и получите один из 17 скинов общества.",
                            ImageUrl = "/images/cases/prisma2.png",
                            Name = "Prisma 2 Case",
                            Price = 2.49m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Секретный агент. Совершенный удар.",
                            ImageUrl = "/images/cases/fracture.png",
                            Name = "Fracture Case",
                            Price = 1.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Яркие скины нового поколения.",
                            ImageUrl = "/images/cases/chroma3.png",
                            Name = "Chroma 3 Case",
                            Price = 3.49m
                        });
                });

            modelBuilder.Entity("CS2Cases.Models.Skin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<float>("DropChance")
                        .HasColumnType("real");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WeaponType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("Skins", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaseId = 1,
                            DropChance = 3.2f,
                            ImageUrl = "/images/skins/ak47_phantom.png",
                            Name = "AK-47 | Phantom Disruptor",
                            Rarity = "Classified",
                            WeaponType = "Rifle"
                        },
                        new
                        {
                            Id = 2,
                            CaseId = 1,
                            DropChance = 3.2f,
                            ImageUrl = "/images/skins/m4a1s_playertwo.png",
                            Name = "M4A1-S | Player Two",
                            Rarity = "Classified",
                            WeaponType = "Rifle"
                        },
                        new
                        {
                            Id = 3,
                            CaseId = 1,
                            DropChance = 0.64f,
                            ImageUrl = "/images/skins/awp_wildfire.png",
                            Name = "AWP | Wildfire",
                            Rarity = "Covert",
                            WeaponType = "Sniper"
                        },
                        new
                        {
                            Id = 4,
                            CaseId = 1,
                            DropChance = 7.9f,
                            ImageUrl = "/images/skins/glock_neonoir.png",
                            Name = "Glock-18 | Neo-Noir",
                            Rarity = "Restricted",
                            WeaponType = "Pistol"
                        },
                        new
                        {
                            Id = 5,
                            CaseId = 1,
                            DropChance = 0.64f,
                            ImageUrl = "/images/skins/deagle_codered.png",
                            Name = "Desert Eagle | Code Red",
                            Rarity = "Covert",
                            WeaponType = "Pistol"
                        },
                        new
                        {
                            Id = 6,
                            CaseId = 1,
                            DropChance = 3.2f,
                            ImageUrl = "/images/skins/usps_cortex.png",
                            Name = "USP-S | Cortex",
                            Rarity = "Classified",
                            WeaponType = "Pistol"
                        },
                        new
                        {
                            Id = 7,
                            CaseId = 1,
                            DropChance = 15.98f,
                            ImageUrl = "/images/skins/p250_inferno.png",
                            Name = "P250 | Inferno",
                            Rarity = "MilSpec",
                            WeaponType = "Pistol"
                        },
                        new
                        {
                            Id = 8,
                            CaseId = 1,
                            DropChance = 15.98f,
                            ImageUrl = "/images/skins/mp9_hydra.png",
                            Name = "MP9 | Hydra",
                            Rarity = "MilSpec",
                            WeaponType = "SMG"
                        },
                        new
                        {
                            Id = 9,
                            CaseId = 1,
                            DropChance = 0.26f,
                            ImageUrl = "/images/skins/karambit_doppler.png",
                            Name = "★ Karambit | Doppler",
                            Rarity = "Gold",
                            WeaponType = "Knife"
                        },
                        new
                        {
                            Id = 10,
                            CaseId = 2,
                            DropChance = 0.64f,
                            ImageUrl = "/images/skins/ak47_ratrod.png",
                            Name = "AK-47 | Rat Rod",
                            Rarity = "Covert",
                            WeaponType = "Rifle"
                        },
                        new
                        {
                            Id = 11,
                            CaseId = 2,
                            DropChance = 0.64f,
                            ImageUrl = "/images/skins/m4a4_toothfairy.png",
                            Name = "M4A4 | Tooth Fairy",
                            Rarity = "Covert",
                            WeaponType = "Rifle"
                        },
                        new
                        {
                            Id = 12,
                            CaseId = 2,
                            DropChance = 3.2f,
                            ImageUrl = "/images/skins/deagle_kumicho.png",
                            Name = "Desert Eagle | Kumicho Dragon",
                            Rarity = "Classified",
                            WeaponType = "Pistol"
                        },
                        new
                        {
                            Id = 13,
                            CaseId = 2,
                            DropChance = 7.9f,
                            ImageUrl = "/images/skins/glock_vogue.png",
                            Name = "Glock-18 | Vogue",
                            Rarity = "Restricted",
                            WeaponType = "Pistol"
                        },
                        new
                        {
                            Id = 14,
                            CaseId = 2,
                            DropChance = 7.9f,
                            ImageUrl = "/images/skins/p90_cocoa.png",
                            Name = "P90 | Cocoa Rampage",
                            Rarity = "Restricted",
                            WeaponType = "SMG"
                        },
                        new
                        {
                            Id = 15,
                            CaseId = 2,
                            DropChance = 0.26f,
                            ImageUrl = "/images/skins/butterfly_fade.png",
                            Name = "★ Butterfly Knife | Fade",
                            Rarity = "Gold",
                            WeaponType = "Knife"
                        });
                });

            modelBuilder.Entity("CS2Cases.Models.UserInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("ObtainedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SkinId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SkinId");

                    b.ToTable("UserInventory", (string)null);
                });

            modelBuilder.Entity("CS2Cases.Models.Skin", b =>
                {
                    b.HasOne("CS2Cases.Models.Case", "Case")
                        .WithMany("Skins")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("CS2Cases.Models.UserInventory", b =>
                {
                    b.HasOne("CS2Cases.Models.Skin", "Skin")
                        .WithMany()
                        .HasForeignKey("SkinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skin");
                });

            modelBuilder.Entity("CS2Cases.Models.Case", b =>
                {
                    b.Navigation("Skins");
                });
#pragma warning restore 612, 618
        }
    }
}
